import React from 'react';
import Head from 'next/head';

const HeadApp = () => {
  return (
    <Head>
      <title>Samlux</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" />
      <link
        href="https://fonts.googleapis.com/css2?family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap"
        rel="stylesheet"
      ></link>
    </Head>
  );
};

export default HeadApp;
